<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>The official .NET library for the OpenAI service API.</Description>
    <AssemblyTitle>OpenAI client library for .NET</AssemblyTitle>

    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OpenAI.Responses\src\OpenAI.Responses.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ClientModel"/>
    <PackageReference Include="System.Net.ServerSentEvents"/>
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
    <PackageReference Include="System.Diagnostics.DiagnosticSource"/>
  </ItemGroup>

</Project>